// PRIME MX · Auditoría IT · Resultado posterior opcional v1
(function(){
'use strict';
const RESULT_BUCKET='audit-resultados';
const MAX_RESULT=10*1024*1024;

const baseNewAudit=newAudit;
newAudit=function(p){const a=baseNewAudit(p);a.score='';a.resultPath=null;a.resultName='';a.resultMime='';a.resultSize=0;a.resultUploadedAt=null;a.resultUrl=null;return a};

const baseFromRow=fromRow;
fromRow=function(r){const a=baseFromRow(r);a.score=r.audit_score==null?'':Number(r.audit_score);a.resultPath=r.result_file_path||null;a.resultName=r.result_file_name||'';a.resultMime=r.result_file_mime||'';a.resultSize=Number(r.result_file_size||0);a.resultUploadedAt=r.result_uploaded_at||null;a.resultUrl=null;return a};

async function signResult(a){if(!a?.resultPath){if(a)a.resultUrl=null;return}const s=await sb.storage.from(RESULT_BUCKET).createSignedUrl(a.resultPath,3600);a.resultUrl=s.error?null:(s.data?.signedUrl||null)}

const baseLoadAll=loadAll;
loadAll=async function(){await baseLoadAll();await Promise.all([...audits.values()].map(signResult));renderAll()};

function resultStyle(){if(document.getElementById('audit-result-style'))return;const s=document.createElement('style');s.id='audit-result-style';s.textContent=`
#audit-result-card{margin-top:14px}.result-grid{display:grid;grid-template-columns:minmax(180px,.35fr) minmax(0,1fr);gap:14px;padding:16px}.result-score-wrap{display:flex;align-items:center;gap:8px}.result-score-wrap input{max-width:150px}.result-score-wrap span{font:600 12px var(--mono);color:var(--muted)}.result-file-box{border:1px dashed var(--line2);border-radius:var(--radius,10px);padding:12px;background:#fff;display:flex;align-items:center;justify-content:space-between;gap:12px;min-height:66px}.result-file-meta b{display:block;font-size:12px}.result-file-meta span{font-size:10.5px;color:var(--muted)}.result-actions{display:flex;gap:7px;flex-wrap:wrap}.result-note{padding:0 16px 16px;color:var(--muted);font-size:11px}.score-pill{display:inline-flex;padding:3px 8px;border-radius:20px;background:var(--brand-soft,#e6f3ef);color:var(--brand,#08775c);font-weight:700;white-space:nowrap}.score-pending{font-size:10px;color:var(--muted)}@media(max-width:800px){.result-grid{grid-template-columns:1fr}}
`;document.head.appendChild(s)}

function ensureResultCard(){resultStyle();let card=$('#audit-result-card');if(card)return card;card=document.createElement('div');card.id='audit-result-card';card.className='module';card.innerHTML=`<div class="module-head"><div><div class="module-title">Resultado de auditoría</div><div class="card-sub">Opcional · puede capturarse al cierre o cuando llegue el resultado posteriormente</div></div><div class="module-meta" id="result-meta">Pendiente</div></div><div class="result-grid"><div><div class="field"><label>Calificación (0–100)</label><div class="result-score-wrap"><input id="a-score" type="number" min="0" max="100" step="0.01" class="control" placeholder="Ej. 96"><span>/ 100</span></div></div><button id="save-result" class="btn primary small can-write" type="button">Guardar calificación</button></div><div><div class="field"><label>Hoja con resultado</label><div id="result-file-box" class="result-file-box"></div></div></div></div><div class="result-note">No es obligatorio para cerrar la auditoría. La calificación y la hoja pueden agregarse después sin modificar el checklist ya cerrado.</div>`;const root=document.querySelector('.audit-main');root?.appendChild(card);$('#save-result').onclick=()=>saveAuditResult(true);return card}

function fmtResultDate(v){if(!v)return'';try{return new Date(v).toLocaleString('es-MX',{dateStyle:'medium',timeStyle:'short'})}catch(_){return''}}
function scoreText(a){return a?.score!==''&&a?.score!=null?Number(a.score).toLocaleString('es-MX',{maximumFractionDigits:2})+'/100':'Pendiente'}

function renderResultCard(a){const card=ensureResultCard();if(!card)return;card.classList.toggle('hidden',!a);if(!a)return;const input=$('#a-score');input.value=a.score===''?'':a.score;input.disabled=!canWrite;$('#save-result').classList.toggle('hidden',!canWrite);$('#result-meta').textContent=(a.score!==''&&a.score!=null)?scoreText(a):(a.resultPath?'Hoja cargada':'Pendiente');const box=$('#result-file-box');if(a.resultPath){box.innerHTML=`<div class="result-file-meta"><b>${esc(a.resultName||'Hoja de resultado')}</b><span>${a.resultSize?Math.round(a.resultSize/1024)+' KB · ':''}${a.resultUploadedAt?esc(fmtResultDate(a.resultUploadedAt)):''}</span></div><div class="result-actions">${a.resultUrl?'<button class="btn small" id="view-result-file" type="button">Ver hoja</button>':''}${canWrite?'<button class="btn small soft" id="upload-result-file" type="button">Cambiar archivo</button>':''}</div>`}else{box.innerHTML=`<div class="result-file-meta"><b>Sin hoja de resultado</b><span>PDF, imagen o Excel · máximo 10 MB</span></div>${canWrite?'<div class="result-actions"><button class="btn small soft" id="upload-result-file" type="button">＋ Subir hoja</button></div>':''}`};$('#view-result-file')?.addEventListener('click',()=>{if(a.resultUrl)window.open(a.resultUrl,'_blank','noopener')});$('#upload-result-file')?.addEventListener('click',()=>chooseResultFile(a));}

const baseLoadAuditForm=loadAuditForm;
loadAuditForm=function(){baseLoadAuditForm();renderResultCard(selectedAudit())};
const baseClearAuditForm=clearAuditForm;
clearAuditForm=function(){baseClearAuditForm();renderResultCard(null)};

function ensureUniverseHeaders(){const tr=document.querySelector('#view-universe table thead tr');if(!tr||tr.querySelector('[data-result-score-head]'))return;const action=tr.lastElementChild,obs=action?.previousElementSibling;const thScore=document.createElement('th');thScore.dataset.resultScoreHead='1';thScore.textContent='Calificación';const thFile=document.createElement('th');thFile.dataset.resultFileHead='1';thFile.textContent='Resultado';tr.insertBefore(thScore,obs||action);tr.insertBefore(thFile,obs||action)}

const baseRenderUniverse=renderUniverse;
renderUniverse=function(){baseRenderUniverse();ensureUniverseHeaders();document.querySelectorAll('#universe-body tr').forEach(tr=>{if(tr.querySelector('[data-result-score-cell]'))return;const open=tr.querySelector('[data-open]'),key=open?.dataset.open,a=key?audits.get(key):null,cells=tr.children,obs=cells[cells.length-2],scoreTd=document.createElement('td'),fileTd=document.createElement('td');scoreTd.dataset.resultScoreCell='1';scoreTd.innerHTML=a?(a.score!==''&&a.score!=null?`<span class="score-pill">${esc(scoreText(a))}</span>`:'<span class="score-pending">Pendiente</span>'):'—';fileTd.innerHTML=a?.resultPath?(a.resultUrl?`<button class="btn small" data-result-open="${esc(key)}">Ver hoja</button>`:'<span class="score-pending">Archivo cargado</span>'):'—';tr.insertBefore(scoreTd,obs);tr.insertBefore(fileTd,obs)});document.querySelectorAll('[data-result-open]').forEach(b=>b.onclick=()=>{const a=audits.get(b.dataset.resultOpen);if(a?.resultUrl)window.open(a.resultUrl,'_blank','noopener')})};

async function ensureAuditSaved(a){if(!a)return false;if(a.isNew){await saveAudit(false)}return !a.isNew}
function currentScore(){const raw=String($('#a-score')?.value??'').trim();if(!raw)return null;const n=Number(raw);if(!Number.isFinite(n)||n<0||n>100)throw new Error('La calificación debe estar entre 0 y 100.');return Math.round(n*100)/100}

async function saveAuditResult(notify){const a=selectedAudit();if(!a||!canWrite)return;try{await ensureAuditSaved(a);const score=currentScore();const r=await sb.rpc('update_audit_result',{p_audit_id:a.id,p_score:score,p_result_path:a.resultPath||null,p_result_name:a.resultName||null,p_result_mime:a.resultMime||null,p_result_size:a.resultSize||null});if(r.error)throw r.error;const row=r.data?.[0]||{};a.score=row.audit_score==null?'':Number(row.audit_score);a.resultPath=row.result_file_path||null;a.resultName=row.result_file_name||'';a.resultMime=row.result_file_mime||'';a.resultSize=Number(row.result_file_size||0);a.resultUploadedAt=row.result_uploaded_at||null;await signResult(a);renderResultCard(a);renderUniverse();if(notify)toast('Resultado de auditoría guardado')}catch(e){alert(e.message||e)}}

function mimeFor(file){if(file.type)return file.type;const ext=String(file.name||'').toLowerCase().split('.').pop();return ext==='pdf'?'application/pdf':ext==='png'?'image/png':ext==='webp'?'image/webp':(ext==='jpg'||ext==='jpeg')?'image/jpeg':ext==='xlsx'?'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet':ext==='xls'?'application/vnd.ms-excel':''}
function allowedResult(file){const ext=String(file.name||'').toLowerCase().split('.').pop();return ['pdf','jpg','jpeg','png','webp','xlsx','xls'].includes(ext)}
function safeName(v){return String(v||'resultado').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9._-]+/g,'_').slice(-100)}
async function chooseResultFile(a){const inp=document.createElement('input');inp.type='file';inp.accept='.pdf,.jpg,.jpeg,.png,.webp,.xlsx,.xls,application/pdf,image/jpeg,image/png,image/webp,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.ms-excel';inp.onchange=async()=>{const f=inp.files?.[0];if(!f)return;if(f.size>MAX_RESULT)return alert('La hoja de resultado no puede superar 10 MB.');if(!allowedResult(f))return alert('Formato no permitido. Usa PDF, JPG, PNG, WebP, XLSX o XLS.');let uploaded=null;try{await ensureAuditSaved(a);const mime=mimeFor(f);if(!mime)throw new Error('No se pudo identificar el tipo de archivo.');const path=`${user.id}/${a.id}/${Date.now()}-${safeName(f.name)}`;const up=await sb.storage.from(RESULT_BUCKET).upload(path,f,{contentType:mime,upsert:false});if(up.error)throw up.error;uploaded=path;const old={path:a.resultPath,name:a.resultName,mime:a.resultMime,size:a.resultSize,at:a.resultUploadedAt,url:a.resultUrl};a.resultPath=path;a.resultName=f.name;a.resultMime=mime;a.resultSize=f.size;a.resultUploadedAt=new Date().toISOString();a.resultUrl=null;try{await saveAuditResult(false)}catch(e){a.resultPath=old.path;a.resultName=old.name;a.resultMime=old.mime;a.resultSize=old.size;a.resultUploadedAt=old.at;a.resultUrl=old.url;throw e}toast('Hoja de resultado cargada');}catch(e){if(uploaded)await sb.storage.from(RESULT_BUCKET).remove([uploaded]).catch(()=>{});alert('No se pudo cargar la hoja: '+(e.message||e))}};inp.click()}

resultStyle();
})();