const PROJECT='ydeusddtqsstqehqhkgi';
const SUPA_URL='https://'+PROJECT+'.supabase.co';
const SUPA_KEY='sb_publishable_3g_w_Iw4bLHE76c073jlQw_YFXMlljK';
const AUTH_KEY='sb-'+PROJECT+'-auth-token';
const REPORT_ID='adquisicion-2026';
const sb=window.supabase.createClient(SUPA_URL,SUPA_KEY,{auth:{storageKey:AUTH_KEY,persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let profile=null, rows=[], selected=new Set();
function norm(v){return v===null||v===undefined?'':String(v).trim()}
function gf(obj,...names){const ks=Object.keys(obj||{});for(const n of names){const t=n.trim().toLowerCase();const k=ks.find(x=>x.trim().toLowerCase()===t);if(k!==undefined)return obj[k]}return ''}
function fail(t,p){$('#gt').textContent=t;$('#gp').textContent=p;$('#ga').classList.remove('hidden')}
function esc(v){return norm(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function equipmentFromLegacy(r){const er=norm(gf(r,'Equipo')).toLowerCase();const equipo=er.includes('laptop')?'Laptop':(er.includes('pc')||er.includes('escritorio')||er.includes('cpu')?'CPU':norm(gf(r,'Equipo'))||'Sin clasificar');return{report_id:REPORT_ID,etiqueta:norm(gf(r,'Etiqueta')),equipo,marca:norm(gf(r,'Marca')),modelo:norm(gf(r,'Modelo')),serie:norm(gf(r,'Serie')),estatus:norm(gf(r,'Estatus','Status'))||'Sin estatus capturado',asignado:norm(gf(r,'Asignado'))||'Sin dato',pdv_asignado:norm(gf(r,'PDV Asignado')),ticket_mesa_ayuda:norm(gf(r,'Ticket Mesa de ayuda')),observaciones:norm(gf(r,'Observaciones')),raw_row:r}}
async function boot(){const s=await sb.auth.getSession();if(!s.data.session)return fail('Sesión no detectada','Entra primero al Portal PRIME MX.');const u=await sb.auth.getUser();if(u.error||!u.data.user)return fail('Sesión no válida','No se pudo validar la sesión central.');const p=await sb.from('profiles').select('nombre,email,role,activo').eq('user_id',u.data.user.id).maybeSingle();if(p.error||!p.data||!p.data.activo)return fail('Cuenta no autorizada','Tu perfil PRIME MX está inactivo o no existe.');const m=await sb.from('app_modules').select('code').eq('code','ADQUISICION').maybeSingle();if(m.error||!m.data)return fail('Sin permiso','Tu cuenta no tiene acceso a Adquisición.');profile=p.data;$('#name').textContent=profile.nombre||profile.email;$('#role').textContent=profile.role;$('#gate').classList.add('hidden');$('#app').classList.remove('hidden');await load();bind()}
async function load(){const r=await sb.from('adq_equipment').select('*').eq('report_id',REPORT_ID).order('etiqueta');if(r.error)throw r.error;rows=r.data||[];const rep=await sb.from('adq_reports').select('*').eq('report_id',REPORT_ID).maybeSingle();$('#meta').textContent=rep.data?.filename?`${rep.data.filename} · ${rows.length.toLocaleString('es-MX')} registros`:'Sin reporte central';renderAll();if(rows.length===0){show('importar')}else{show('reporte')}}
function renderAll(){const total=rows.length,cpu=rows.filter(r=>r.equipo==='CPU').length,lap=rows.filter(r=>r.equipo==='Laptop').length,assigned=rows.filter(r=>/^s[ií]$/i.test(norm(r.asignado))||r.pdv_asignado).length;$('#kTotal').textContent=total.toLocaleString('es-MX');$('#kCPU').textContent=cpu.toLocaleString('es-MX');$('#kLap').textContent=lap.toLocaleString('es-MX');$('#kAss').textContent=assigned.toLocaleString('es-MX');$('#navCount').textContent=total;renderStatus();populateFilters();renderTable();renderAssign();loadHistory()}
function renderStatus(){const map={};for(const r of rows){const k=norm(r.estatus)||'Sin estatus';map[k]=(map[k]||0)+1}const total=rows.length;$('#statusGrid').innerHTML=Object.entries(map).sort((a,b)=>b[1]-a[1]).map(([k,n])=>`<div class="status"><div class="n">${n}</div><div class="l">${esc(k)}</div><small>${total?(n/total*100).toFixed(1):0}% del total</small></div>`).join('')||'<div class="empty">Sin datos</div>'}
function populateFilters(){const fill=(id,vals,prefix)=>{const el=$(id),cur=el.value;el.innerHTML=`<option value="">${prefix}: todos</option>`+[...new Set(vals.filter(Boolean))].sort().map(v=>`<option>${esc(v)}</option>`).join('');if([...el.options].some(o=>o.value===cur))el.value=cur};fill('#fEquipo',rows.map(r=>r.equipo),'Equipo');fill('#fEstatus',rows.map(r=>r.estatus),'Estatus');fill('#fMarca',rows.map(r=>r.marca),'Marca');fill('#aEstatusFilter',rows.map(r=>r.estatus),'Estatus')}
function filtered(){const q=$('#q').value.toLowerCase(),eq=$('#fEquipo').value,es=$('#fEstatus').value,ma=$('#fMarca').value;return rows.filter(r=>(!eq||r.equipo===eq)&&(!es||r.estatus===es)&&(!ma||r.marca===ma)&&(!q||[r.etiqueta,r.equipo,r.marca,r.modelo,r.serie,r.pdv_asignado,r.estatus].some(v=>norm(v).toLowerCase().includes(q))))}
function badgeStatus(v){const s=norm(v).toLowerCase();const c=s.includes('dañ')?'bad':s.includes('almac')?'warn':(s.includes('asign')||s.includes('expansion')||s.includes('expansión'))?'ok':'';return `<span class="badge ${c}">${esc(v||'—')}</span>`}
function renderTable(){const f=filtered();$('#resultCount').textContent=`${f.length.toLocaleString('es-MX')} resultados`;$('#tbody').innerHTML=f.map(r=>`<tr><td>${esc(r.etiqueta)}</td><td>${esc(r.equipo)}</td><td>${esc([r.marca,r.modelo].filter(Boolean).join(' '))}</td><td>${esc(r.serie)}</td><td>${badgeStatus(r.estatus)}</td><td>${esc(r.asignado)}</td><td>${esc(r.pdv_asignado)}</td><td>${esc(r.ticket_mesa_ayuda)}</td></tr>`).join('')||'<tr><td colspan="8" class="empty">Sin resultados</td></tr>'}
function assignFiltered(){const q=$('#aq').value.toLowerCase(),es=$('#aEstatusFilter').value;return rows.filter(r=>(!es||r.estatus===es)&&(!q||[r.etiqueta,r.serie,r.marca,r.modelo,r.pdv_asignado].some(v=>norm(v).toLowerCase().includes(q))))}
function renderAssign(){const f=assignFiltered();$('#aCount').textContent=`${f.length} encontrados`;$('#selCount').textContent=`${selected.size} seleccionados`;$('#atbody').innerHTML=f.slice(0,600).map(r=>`<tr><td><input type="checkbox" class="pick" data-id="${r.id}" ${selected.has(r.id)?'checked':''}></td><td>${esc(r.etiqueta)}</td><td>${esc(r.equipo)}</td><td>${esc([r.marca,r.modelo].filter(Boolean).join(' '))}</td><td>${esc(r.serie)}</td><td>${badgeStatus(r.estatus)}</td><td>${esc(r.pdv_asignado)}</td><td><button class="btn small correct" data-id="${r.id}">Corregir</button></td></tr>`).join('')||'<tr><td colspan="8" class="empty">Sin resultados</td></tr>';$$('.pick').forEach(x=>x.onchange=()=>{x.checked?selected.add(x.dataset.id):selected.delete(x.dataset.id);renderAssign()});$$('.correct').forEach(x=>x.onclick=()=>correctRow(x.dataset.id))}
async function correctRow(id){if(!canWrite())return;const r=rows.find(x=>x.id===id);if(!r)return;const marca=prompt('Marca',r.marca||'');if(marca===null)return;const modelo=prompt('Modelo',r.modelo||'');if(modelo===null)return;const serie=prompt('Serie',r.serie||'');if(serie===null)return;const u=await sb.from('adq_equipment').update({marca:marca.trim(),modelo:modelo.trim(),serie:serie.trim(),updated_by:(await sb.auth.getUser()).data.user.id,updated_at:new Date().toISOString()}).eq('id',id);if(u.error)return alert(u.error.message);await audit('Corregir datos',`${r.etiqueta} → Marca/Modelo/Serie`,1);await load()}
function canWrite(){if(!['ADMIN','CAPTURA'].includes(profile.role)){alert('Tu rol es solo consulta.');return false}return true}
async function applyBulk(){if(!canWrite()||selected.size===0)return alert('Selecciona al menos un equipo.');const pdv=$('#bPDV').value.trim(),estatus=$('#bEstatus').value.trim(),ticket=$('#bTicket').value.trim(),obs=$('#bObs').value.trim();if(!pdv&&!estatus&&!ticket&&!obs)return alert('Captura al menos un cambio.');if(!confirm(`Aplicar cambios a ${selected.size} equipo(s)?`))return;const patch={updated_at:new Date().toISOString()};const user=(await sb.auth.getUser()).data.user;patch.updated_by=user.id;if(pdv){patch.pdv_asignado=pdv;patch.asignado='Sí'}if(estatus)patch.estatus=estatus;if(ticket)patch.ticket_mesa_ayuda=ticket;if(obs)patch.observaciones=obs;const u=await sb.from('adq_equipment').update(patch).in('id',[...selected]);if(u.error)return alert(u.error.message);await audit('Aplicar cambios',[pdv&&`PDV=${pdv}`,estatus&&`Estatus=${estatus}`,ticket&&`Ticket=${ticket}`,obs&&'Observaciones actualizadas'].filter(Boolean).join(', '),selected.size);selected.clear();$('#bPDV').value=$('#bEstatus').value=$('#bTicket').value=$('#bObs').value='';await load()}
async function mergeStatus(){if(!canWrite())return;const from=$('#mFrom').value.trim(),to=$('#mTo').value.trim();if(!from||!to||from===to)return alert('Indica dos valores distintos.');const n=rows.filter(r=>r.estatus===from).length;if(!n)return alert('No hay equipos con ese estatus.');if(!confirm(`Cambiar ${n} equipo(s) de “${from}” a “${to}”?`))return;const user=(await sb.auth.getUser()).data.user;const u=await sb.from('adq_equipment').update({estatus:to,updated_by:user.id,updated_at:new Date().toISOString()}).eq('report_id',REPORT_ID).eq('estatus',from);if(u.error)return alert(u.error.message);await audit('Fusionar Estatus',`“${from}” → “${to}”`,n);await load()}
async function audit(action,details,count){await sb.from('adq_audit_events').insert({report_id:REPORT_ID,action,details,affected_count:count,source_user:profile.email||profile.nombre,source_timestamp:new Date().toISOString()})}
async function loadHistory(){const h=await sb.from('adq_audit_events').select('*').eq('report_id',REPORT_ID).order('source_timestamp',{ascending:false,nullsFirst:false}).order('created_at',{ascending:false}).limit(100);if(h.error)return;$('#histbody').innerHTML=(h.data||[]).map(e=>`<tr><td>${esc(new Date(e.source_timestamp||e.created_at).toLocaleString('es-MX'))}</td><td>${esc(e.source_user||'—')}</td><td>${esc(e.action)}</td><td>${esc(e.details)}</td><td>${esc(e.affected_count??'')}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">Sin historial</td></tr>'}
async function importBackup(file){if(profile.role!=='ADMIN')throw new Error('La migración inicial solo puede ejecutarla ADMIN.');const txt=await file.text(),b=JSON.parse(txt);if(b.kind!=='PrimeMX_Adquisicion_Backup'||b.reportId!==REPORT_ID)throw new Error('El archivo no corresponde al respaldo de Adquisición 2026.');const legacyRows=b.report?.rows;if(!Array.isArray(legacyRows)||!legacyRows.length)throw new Error('El respaldo no contiene filas.');const parsed=legacyRows.map(equipmentFromLegacy).filter(r=>r.etiqueta);const meta=b.report?.meta||{};$('#impInfo').textContent=`Validado: ${parsed.length} filas · ${(b.audit?.entries||[]).length} movimientos. Importando…`;$('#impBar').style.width='5%';const user=(await sb.auth.getUser()).data.user;let q=await sb.from('adq_reports').upsert({report_id:REPORT_ID,filename:meta.filename||'Respaldo legado',sheet_name:meta.sheetName||'BD Homologada',row_count:parsed.length,source_uploaded_by:meta.uploadedBy||null,source_uploaded_at:meta.uploadedAt||null,imported_from_legacy:true,updated_by:user.id,updated_at:new Date().toISOString()},{onConflict:'report_id'});if(q.error)throw q.error;for(let i=0;i<parsed.length;i+=100){const chunk=parsed.slice(i,i+100).map(r=>({...r,updated_by:user.id}));q=await sb.from('adq_equipment').upsert(chunk,{onConflict:'report_id,etiqueta'});if(q.error)throw q.error;$('#impBar').style.width=(10+70*Math.min(1,(i+chunk.length)/parsed.length))+'%'}const entries=Array.isArray(b.audit?.entries)?b.audit.entries:[];for(let i=0;i<entries.length;i+=100){const chunk=entries.slice(i,i+100).map((e,j)=>({report_id:REPORT_ID,action:norm(e.action)||'Movimiento legado',details:norm(e.details),affected_count:Number.isFinite(Number(e.count))?Number(e.count):null,source_user:norm(e.user),source_timestamp:e.timestamp||null,legacy_index:i+j,legacy_payload:e}));q=await sb.from('adq_audit_events').upsert(chunk,{onConflict:'report_id,legacy_index'});if(q.error)throw q.error;$('#impBar').style.width=(80+15*Math.min(1,(i+chunk.length)/Math.max(1,entries.length)))+'%'}const existing=await sb.from('adq_audit_events').select('id',{count:'exact',head:true}).eq('report_id',REPORT_ID).eq('action','Migración central inicial');if(!existing.count)await audit('Migración central inicial',`Respaldo importado: ${parsed.length} filas · ${entries.length} movimientos`,parsed.length);const check=await sb.from('adq_equipment').select('id',{count:'exact',head:true}).eq('report_id',REPORT_ID);if(check.error||check.count!==parsed.length)throw new Error(`Verificación falló: se esperaban ${parsed.length} filas y hay ${check.count??'?'}.`);$('#impBar').style.width='100%';$('#impInfo').textContent=`IMPORTACIÓN OK ✓ ${check.count} filas y ${entries.length} movimientos preservados.`;setTimeout(load,900)}
async function uploadXlsx(file){if(!canWrite())return;const data=new Uint8Array(await file.arrayBuffer());const wb=XLSX.read(data,{type:'array'}),sheet=wb.SheetNames.find(n=>n.toLowerCase().includes('homologada'))||wb.SheetNames[0],json=XLSX.utils.sheet_to_json(wb.Sheets[sheet],{defval:''});const existing=new Set(rows.map(r=>r.etiqueta));const news=json.map(equipmentFromLegacy).filter(r=>r.etiqueta&&!existing.has(r.etiqueta));if(!news.length)return alert('No hay etiquetas nuevas. Los equipos existentes no se sobrescriben.');if(!confirm(`Agregar ${news.length} equipo(s) nuevos sin modificar los existentes?`))return;const user=(await sb.auth.getUser()).data.user;for(let i=0;i<news.length;i+=100){const q=await sb.from('adq_equipment').insert(news.slice(i,i+100).map(r=>({...r,updated_by:user.id})));if(q.error)return alert(q.error.message)}await sb.from('adq_reports').upsert({report_id:REPORT_ID,filename:file.name,sheet_name:sheet,row_count:rows.length+news.length,source_uploaded_by:profile.email||profile.nombre,source_uploaded_at:new Date().toISOString(),updated_by:user.id,updated_at:new Date().toISOString()},{onConflict:'report_id'});await audit('Agregar equipos desde Excel',`${file.name} · ${news.length} etiquetas nuevas`,news.length);await load()}
function exportCsv(){const list=filtered(),cols=['etiqueta','equipo','marca','modelo','serie','estatus','asignado','pdv_asignado','ticket_mesa_ayuda','observaciones'];const txt=[cols.join(','),...list.map(r=>cols.map(c=>'"'+norm(r[c]).replace(/"/g,'""')+'"').join(','))].join('\n');const u=URL.createObjectURL(new Blob(['\ufeff'+txt],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=u;a.download='adquisicion_2026_central.csv';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function show(id){$$('.section').forEach(x=>x.classList.toggle('active',x.id==='s-'+id));$$('.navbtn').forEach(x=>x.classList.toggle('active',x.dataset.s===id));$('#topTitle').textContent=({reporte:'Adquisición equipo de cómputo 2026',asignar:'Asignar equipo',historial:'Historial de movimientos',importar:'Importar / actualizar'})[id]||'Adquisición';if(id==='asignar')renderAssign();if(id==='historial')loadHistory()}
function bind(){$$('.navbtn').forEach(x=>x.onclick=()=>show(x.dataset.s));['#q','#fEquipo','#fEstatus','#fMarca'].forEach(s=>$(s).addEventListener(s==='#q'?'input':'change',renderTable));$('#aq').oninput=renderAssign;$('#aEstatusFilter').onchange=renderAssign;$('#applyBulk').onclick=applyBulk;$('#mergeBtn').onclick=mergeStatus;$('#exportBtn').onclick=exportCsv;$('#backupFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{await importBackup(f)}catch(err){$('#impInfo').textContent='ERROR: '+(err.message||err);$('#impBar').style.width='0'}};$('#xlsxFile').onchange=e=>{const f=e.target.files[0];if(f)uploadXlsx(f)};$('#portalBtn').onclick=()=>location.href='../'}
boot().catch(e=>fail('No se pudo cargar Adquisición',e.message||String(e)));