const STEP_LABELS=['Tienda','HUB','Equipos','Confirmar'];
const VIEW_META={dashboard:['Dashboard','Resumen operativo de recolección de equipos obsoletos.'],request:['Nueva solicitud','Captura guiada de tienda, HUB, equipos y evidencias.'],history:['Historial','Consulta, impresión y exportación de solicitudes.'],hubs:['Directorio HUBs','Administración de destinos y responsables de recepción.']};
function showView(v){document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id==='view-'+v));document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.view===v));const meta=VIEW_META[v]||VIEW_META.dashboard;$('#viewTitle').textContent=meta[0];$('#viewSub').textContent=meta[1];if(v==='dashboard')renderDashboard();if(v==='request')renderWizard();if(v==='history')renderHistory();if(v==='hubs')renderHubs();window.scrollTo({top:0,behavior:'smooth'})}
function renderAll(){renderDashboard();renderWizard();renderHistory();renderHubs();$('#navReqCount').textContent=requests.length;$('#navHubCount').textContent=hubs.length;$('#addHubBtn').classList.toggle('hidden',role!=='ADMIN')}
function renderDashboard(){const eq=requests.reduce((n,r)=>n+r.equipment.length,0);$('#kReq').textContent=requests.length;$('#kEq').textContent=eq;$('#kStore').textContent=stores.length;$('#kHub').textContent=hubs.length;const f=$('#recent');f.innerHTML=requests.length?requests.slice(0,7).map(r=>`<div class="feed-item"><b>${esc(r.store.name)}</b><span>${r.equipment.length} equipo(s) → ${esc(r.hub.name)} · ${fmt(r.date)} · ${esc(r.folio)}</span></div>`).join(''):'<div class="empty">Aún no hay solicitudes. Registra la primera desde Nueva solicitud.</div>'}
function renderWizard(){document.querySelectorAll('.step').forEach((x,i)=>{x.classList.toggle('active',i+1===draft.step);x.classList.toggle('done',i+1<draft.step)});document.querySelectorAll('.stage').forEach((x,i)=>x.classList.toggle('active',i+1===draft.step));if(draft.step===1)renderStoreChoices();if(draft.step===2)renderHubChoices();if(draft.step===3)renderEquipment();if(draft.step===4)renderConfirm();$('#backStep').style.visibility=draft.step===1?'hidden':'visible';const b=$('#nextStep');b.textContent=draft.step===4?'Confirmar y registrar':'Continuar';b.onclick=draft.step===4?saveRequest:()=>moveStep(1)}
function moveStep(d){if(d>0){if(draft.step===1&&!draft.store)return toast('Selecciona una tienda.',true);if(draft.step===2&&!draft.hub)return toast('Selecciona un HUB.',true);if(draft.step===3){collectEquipmentInputs();if(!draft.equipment.length)return toast('Agrega al menos un equipo.',true);if(draft.equipment.some(x=>!x.serial.trim()))return toast('Todos los equipos requieren serie.',true);if(draft.equipment.some(x=>!x.photo))return toast('Todos los equipos requieren foto.',true)}if(draft.step<4)draft.step++}else if(draft.step>1)draft.step--;renderWizard()}
function renderStoreChoices(){const q=($('#storeSearch').value||'').toLowerCase(),list=stores.filter(s=>!q||(s.nombre+' '+s.clave).toLowerCase().includes(q));$('#storeCount').textContent=stores.length+' tiendas';$('#storeList').innerHTML=list.map(s=>`<button class="pick ${draft.store?.id===s.id?'active':''}" onclick="pickStore(${s.id})"><b>${esc(s.nombre)}</b><span>${esc(s.clave)}</span></button>`).join('')||'<div class="empty">Sin resultados</div>'}
function pickStore(id){const s=stores.find(x=>x.id===id);draft.store=s?{id:s.id,name:s.nombre,key:s.clave}:null;renderStoreChoices()}
function renderHubChoices(){const q=($('#hubSearch').value||'').toLowerCase(),reg=$('#hubRegion').value;const regs=[...new Set(hubs.map(h=>h.region))].sort();const cur=$('#hubRegion').value;$('#hubRegion').innerHTML='<option value="">Todas las regiones</option>'+regs.map(r=>`<option ${r===cur?'selected':''}>${esc(r)}</option>`).join('');const list=hubs.filter(h=>(!q||(h.hub+' '+h.ciudad+' '+h.estado+' '+(h.responsable||'')).toLowerCase().includes(q))&&(!reg||h.region===reg));$('#hubList').innerHTML=list.map(h=>`<button class="pick ${draft.hub?.id===h.id?'active':''}" onclick="pickHub(${h.id})"><b>${esc(h.hub)}</b><span>${esc(h.region)} · ${esc(h.ciudad)}, ${esc(h.estado)}</span><span>${esc(h.responsable||'Sin responsable')}</span></button>`).join('')||'<div class="empty">Sin resultados</div>'}
function pickHub(id){const h=hubs.find(x=>x.id===id);draft.hub=h?{id:h.id,name:h.hub,city:h.ciudad,state:h.estado,owner:h.responsable||'',phone:h.telefono||'',region:h.region}:null;renderHubChoices()}
function addEquipment(){collectEquipmentInputs();draft.equipment.push({id:uuid(),type:'CPU',serial:'',condition:'Obsoleto',notes:'',photo:null,photoName:'',photoSize:0});renderEquipment()}
function removeEquipment(i){collectEquipmentInputs();draft.equipment.splice(i,1);renderEquipment()}
function collectEquipmentInputs(){document.querySelectorAll('.eq').forEach((x,i)=>{if(!draft.equipment[i])return;draft.equipment[i].type=x.querySelector('.etype').value;draft.equipment[i].serial=x.querySelector('.eserial').value;draft.equipment[i].condition=x.querySelector('.econd').value;draft.equipment[i].notes=x.querySelector('.enotes').value})}
function renderEquipment(){if(!draft.equipment.length)addEquipment();$('#eqList').innerHTML=draft.equipment.map((e,i)=>`<div class="eq"><div class="eqhead"><b>Equipo #${i+1}</b><button class="btn bad sm" onclick="removeEquipment(${i})">Quitar</button></div><div class="eqgrid"><div class="field"><label>Tipo</label><select class="etype">${EQ_TYPES.map(x=>`<option ${x===e.type?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Número de serie *</label><input class="inp eserial" value="${esc(e.serial)}" placeholder="Serie"></div><div class="field"><label>Condición</label><select class="econd">${EQ_COND.map(x=>`<option ${x===e.condition?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Notas</label><input class="inp enotes" value="${esc(e.notes)}" placeholder="Opcional"></div><div class="field full"><label>Evidencia fotográfica *</label>${e.photo?`<div class="photoprev"><img src="${e.photo}" onclick="showDraftPhoto(${i})"><div><b>${esc(e.photoName||'foto.jpg')}</b><br><span style="font-size:11px;color:var(--muted)">${Math.round((e.photoSize||0)/1024)} KB</span></div><button class="btn sm" onclick="choosePhoto(${i})">Cambiar</button></div>`:`<div class="photozone" onclick="choosePhoto(${i})">Subir foto del equipo · procura que se vea la serie</div>`}<input type="file" id="photo-${i}" accept="image/*" capture="environment" class="hidden" onchange="photoChanged(event,${i})"></div></div></div>`).join('')}
function choosePhoto(i){$('#photo-'+i).click()}
async function photoChanged(ev,i){const f=ev.target.files[0];if(!f)return;try{const p=await compressPhoto(f);draft.equipment[i].photo=p.data;draft.equipment[i].photoName=p.name;draft.equipment[i].photoSize=p.size;renderEquipment();toast('Foto agregada')}catch(e){toast('No se pudo procesar la foto.',true)}}
function showDraftPhoto(i){showPhoto(draft.equipment[i]?.photo)}
function renderConfirm(){$('#confirm').innerHTML=`<div class="summary"><div class="box"><b>Tienda</b><span>${esc(draft.store?.name)}</span></div><div class="box"><b>Clave PDV</b><span>${esc(draft.store?.key)}</span></div><div class="box"><b>HUB destino</b><span>${esc(draft.hub?.name)}</span></div><div class="box"><b>Responsable HUB</b><span>${esc(draft.hub?.owner||'—')}</span></div></div><div class="field"><label>Persona que entrega *</label><input id="deliverer" class="inp" value="${esc(draft.deliverer)}"></div><div class="table-wrap"><table><thead><tr><th>#</th><th>Tipo</th><th>Serie</th><th>Condición</th><th>Foto</th></tr></thead><tbody>${draft.equipment.map((e,i)=>`<tr><td>${i+1}</td><td>${esc(e.type)}</td><td>${esc(e.serial)}</td><td>${esc(e.condition)}</td><td>${e.photo?'✓':'—'}</td></tr>`).join('')}</tbody></table></div>`}
function resetDraft(){draft={step:1,store:null,hub:null,equipment:[],deliverer:profile.nombre||profile.email||me.email};renderWizard()}
function renderHistory(){const q=($('#histSearch').value||'').toLowerCase();const list=requests.filter(r=>!q||(r.folio+' '+r.store.name+' '+r.store.key+' '+r.hub.name+' '+r.deliverer).toLowerCase().includes(q));$('#histCount').textContent=requests.length+' solicitudes';$('#historyList').innerHTML=list.map(r=>`<div class="req" id="r-${r.id}"><div class="reqtop" onclick="$('#r-${r.id}').classList.toggle('open')"><div><b>${esc(r.folio)} · ${esc(r.store.name)}</b><span>${fmt(r.date)} · ${esc(r.hub.name)} · Entrega: ${esc(r.deliverer||'—')}</span></div><div>${r.equipment.length} equipo(s)</div></div><div class="reqbody"><div class="table-wrap"><table><thead><tr><th>Foto</th><th>Tipo</th><th>Serie</th><th>Condición</th><th>Notas</th></tr></thead><tbody>${r.equipment.map(e=>`<tr><td>${e.photo?`<img class="thumb" src="${e.photo}" onclick="event.stopPropagation();showPhoto('${e.photo}')">`:'—'}</td><td>${esc(e.type)}</td><td>${esc(e.serial)}</td><td>${esc(e.condition)}</td><td>${esc(e.notes||'')}</td></tr>`).join('')}</tbody></table></div><div class="rowend"><button class="btn sm" onclick="printLetter('${r.id}')">Imprimir carta</button>${role==='ADMIN'?`<button class="btn bad sm" onclick="deleteRequest('${r.id}')">Eliminar</button>`:''}</div></div></div>`).join('')||'<div class="empty">No hay solicitudes.</div>'}
function showPhoto(url){if(!url)return;$('#fullPhoto').src=url;$('#photoModal').classList.add('show')}
function renderHubs(){const q=($('#dirSearch').value||'').toLowerCase(),list=hubs.filter(h=>!q||(h.hub+' '+h.ciudad+' '+h.estado+' '+h.region+' '+(h.responsable||'')).toLowerCase().includes(q));$('#hubDirCount').textContent=hubs.length+' HUBs';$('#hubGrid').innerHTML=list.map(h=>`<div class="hub"><div class="reg">${esc(h.region)}</div><h3>${esc(h.hub)}</h3><p>${esc(h.ciudad)}, ${esc(h.estado)}</p><p>${esc(h.responsable||'Sin responsable')} · ${esc(h.telefono||'Sin teléfono')}</p>${role==='ADMIN'?`<div class="actions"><button class="btn sm" onclick="editHub(${h.id})">Editar</button><button class="btn bad sm" onclick="retireHub(${h.id})">Retirar</button></div>`:''}</div>`).join('')}
document.addEventListener('click',e=>{const t=e.target.closest('.tab');if(t)showView(t.dataset.view)});
document.addEventListener('DOMContentLoaded',()=>{$('#backStep').onclick=()=>moveStep(-1);$('#nextStep').onclick=()=>moveStep(1);$('#addEq').onclick=addEquipment;$('#newReq').onclick=()=>{resetDraft();showView('request')};$('#exportCsv').onclick=exportCSV;$('#addHubBtn').onclick=addHub;$('#storeSearch').oninput=renderStoreChoices;$('#hubSearch').oninput=renderHubChoices;$('#hubRegion').onchange=renderHubChoices;$('#histSearch').oninput=renderHistory;$('#dirSearch').oninput=renderHubs;$('#logoutBtn').onclick=async()=>{await sb.auth.signOut();location.href='../'};$('#photoModal').onclick=e=>{if(e.target.id==='photoModal')e.currentTarget.classList.remove('show')};init()});
