const PROJECT='ydeusddtqsstqehqhkgi';
const SB_URL='https://'+PROJECT+'.supabase.co';
const SB_KEY='sb_publishable_3g_w_Iw4bLHE76c073jlQw_YFXMlljK';
const AUTH_KEY='sb-'+PROJECT+'-auth-token';
const sb=window.supabase.createClient(SB_URL,SB_KEY,{auth:{storageKey:AUTH_KEY,persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const EQ_TYPES=['CPU','Laptop','Monitor','Impresora','Otro'];
const EQ_COND=['Obsoleto','Dañado','Funcional (baja)'];
let me=null,profile=null,role='CONSULTA',stores=[],hubs=[],requests=[];
let draft={step:1,store:null,hub:null,equipment:[],deliverer:''};
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(t,bad=false){document.querySelector('.toast')?.remove();const x=document.createElement('div');x.className='toast'+(bad?' bad':'');x.textContent=t;document.body.appendChild(x);setTimeout(()=>x.remove(),3500)}
function fmt(iso){const d=new Date(iso);return d.toLocaleDateString('es-MX',{day:'2-digit',month:'short',year:'numeric'})+' · '+d.toLocaleTimeString('es-MX',{hour:'2-digit',minute:'2-digit'})}
function uuid(){return crypto.randomUUID()}
function folio(){const d=new Date(),ymd=d.getFullYear()+String(d.getMonth()+1).padStart(2,'0')+String(d.getDate()).padStart(2,'0');return 'PRM-'+ymd+'-'+String(Math.floor(1000+Math.random()*9000))}
function dataUrlBlob(u){const [h,d]=String(u||'').split(',');if(!h||!d)throw new Error('Foto inválida');const mime=(h.match(/data:([^;]+)/)||[])[1]||'image/jpeg',bin=atob(d),arr=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)arr[i]=bin.charCodeAt(i);return{blob:new Blob([arr],{type:mime}),mime}}
function ext(m){return m==='image/png'?'png':m==='image/webp'?'webp':'jpg'}
async function auth(){const s=await sb.auth.getSession();if(!s.data.session){location.href='../';return false}const u=await sb.auth.getUser();if(u.error||!u.data.user){await sb.auth.signOut();location.href='../';return false}me=u.data.user;const p=await sb.from('profiles').select('nombre,email,role,activo').eq('user_id',me.id).maybeSingle();if(p.error||!p.data||!p.data.activo){await sb.auth.signOut();location.href='../';return false}const m=await sb.from('app_modules').select('code').eq('code','HUB').maybeSingle();if(m.error||!m.data){alert('Tu cuenta no tiene permiso para HUB.');location.href='../';return false}profile=p.data;role=p.data.role;draft.deliverer=p.data.nombre||p.data.email||me.email;return true}
async function loadData(){const [s,h,r,e]=await Promise.all([sb.from('hub_stores').select('id,nombre,clave').eq('activo',true).order('nombre'),sb.from('hub_locations').select('id,region,estado,ciudad,hub,responsable,telefono').eq('activo',true).order('region').order('hub'),sb.from('hub_requests').select('*').order('requested_at',{ascending:false}),sb.from('hub_equipment').select('*').order('created_at',{ascending:true})]);for(const x of[s,h,r,e])if(x.error)throw x.error;stores=s.data||[];hubs=h.data||[];const paths=(e.data||[]).map(x=>x.foto_path).filter(Boolean),signed=new Map();if(paths.length){const su=await sb.storage.from('hub-evidencias').createSignedUrls(paths,900);if(!su.error)(su.data||[]).forEach((x,i)=>{if(x?.signedUrl)signed.set(paths[i],x.signedUrl)})}const by=new Map();(e.data||[]).forEach(x=>{if(!by.has(x.request_id))by.set(x.request_id,[]);by.get(x.request_id).push({id:x.id,type:x.tipo,serial:x.serial,condition:x.condicion,notes:x.notas||'',photoPath:x.foto_path,photo:signed.get(x.foto_path)||null,photoName:x.foto_name||'',photoSize:x.foto_size||0})});requests=(r.data||[]).map(x=>({id:x.id,folio:x.folio,date:x.requested_at,store:{id:x.store_id,name:x.store_nombre,key:x.store_clave||''},hub:{id:x.hub_id,name:x.hub_nombre,city:x.hub_ciudad||'',state:x.hub_estado||'',owner:x.hub_responsable||'',phone:x.hub_telefono||''},deliverer:x.entregado_por_nombre||'',createdBy:x.created_by,equipment:by.get(x.id)||[]}))}
async function compressPhoto(file){return new Promise((resolve,reject)=>{const fr=new FileReader();fr.onerror=reject;fr.onload=()=>{const im=new Image();im.onerror=reject;im.onload=()=>{let w=im.width,h=im.height,max=1000;if(w>max||h>max){const r=Math.min(max/w,max/h);w=Math.round(w*r);h=Math.round(h*r)}const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(im,0,0,w,h);resolve({data:c.toDataURL('image/jpeg',.78),name:file.name,size:file.size})};im.src=fr.result};fr.readAsDataURL(file)})}
async function saveRequest(){if(role!=='ADMIN'&&role!=='CAPTURA')return toast('Tu rol es solo consulta.',true);collectEquipmentInputs();const deliverer=($('#deliverer')?.value||draft.deliverer||'').trim();if(!draft.store||!draft.hub)return toast('Falta tienda o HUB.',true);if(!draft.equipment.length)return toast('Agrega al menos un equipo.',true);if(draft.equipment.some(x=>!x.serial.trim()))return toast('Todos los equipos requieren serie.',true);if(draft.equipment.some(x=>!x.photo))return toast('Todos los equipos requieren foto.',true);if(!deliverer)return toast('Captura la persona que entrega.',true);const btn=$('#nextStep');if(btn){btn.disabled=true;btn.textContent='Guardando…'}const reqId=uuid(),f=folio(),now=new Date().toISOString(),uploaded=[],rows=[];try{for(const q of draft.equipment){const eqId=uuid(),z=dataUrlBlob(q.photo),path=`${me.id}/${reqId}/${eqId}.${ext(z.mime)}`;const up=await sb.storage.from('hub-evidencias').upload(path,z.blob,{contentType:z.mime,upsert:false});if(up.error)throw up.error;uploaded.push(path);rows.push({id:eqId,tipo:q.type,serial:q.serial.trim(),condicion:q.condition,notas:q.notes.trim(),foto_path:path,foto_name:q.photoName||null,foto_size:q.photoSize||null})}const rq={id:reqId,folio:f,requested_at:now,store_id:draft.store.id,store_nombre:draft.store.name,store_clave:draft.store.key,hub_id:draft.hub.id,hub_nombre:draft.hub.name,hub_ciudad:draft.hub.city,hub_estado:draft.hub.state,hub_responsable:draft.hub.owner||null,hub_telefono:draft.hub.phone||null,entregado_por_nombre:deliverer};const rpc=await sb.rpc('create_hub_request',{p_request:rq,p_equipment:rows});if(rpc.error)throw rpc.error;await loadData();draft={step:1,store:null,hub:null,equipment:[],deliverer:profile.nombre||profile.email||me.email};renderAll();showView('history');toast('Solicitud '+f+' registrada');setTimeout(()=>printLetter(reqId,false),300)}catch(e){if(uploaded.length)await sb.storage.from('hub-evidencias').remove(uploaded);toast('No se pudo registrar: '+(e.message||e),true)}finally{if(btn){btn.disabled=false;btn.textContent='Confirmar y registrar'}}}
async function deleteRequest(id){if(role!=='ADMIN')return;const r=requests.find(x=>x.id===id);if(!r||!confirm('¿Eliminar '+r.folio+' y toda su evidencia? Esta acción no se puede deshacer.'))return;const paths=r.equipment.map(x=>x.photoPath).filter(Boolean);if(paths.length){const rm=await sb.storage.from('hub-evidencias').remove(paths);if(rm.error)return toast('No se eliminó la evidencia: '+rm.error.message,true)}const d=await sb.from('hub_requests').delete().eq('id',id);if(d.error)return toast(d.error.message,true);await loadData();renderAll();toast('Solicitud y evidencia eliminadas')}
function printLetter(id,auto=true){const r=requests.find(x=>x.id===id);if(!r)return toast('Solicitud no encontrada.',true);const w=window.open('','_blank','width=920,height=760');if(!w)return toast('Permite ventanas emergentes.',true);w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${esc(r.folio)}</title><style>body{font:14px Arial;margin:42px;color:#111}h1{font-size:22px;margin:0}.sub{color:#555;margin-top:5px}.box{border:1px solid #bbb;border-radius:8px;padding:15px;margin:20px 0}.row{display:flex;justify-content:space-between;gap:20px;margin:7px 0}.k{color:#666}.v{font-weight:bold;text-align:right}table{width:100%;border-collapse:collapse}th,td{border:1px solid #bbb;padding:8px;text-align:left}th{background:#f3f3f3}.sign{display:grid;grid-template-columns:1fr 1fr;gap:80px;margin-top:80px}.line{border-top:1px solid #111;text-align:center;padding-top:8px}.foot{margin-top:30px;font-size:11px;color:#666}</style></head><body><h1>PRIME MX · Carta de entrega de equipo</h1><div class="sub">Folio ${esc(r.folio)} · ${esc(fmt(r.date))}</div><div class="box"><div class="row"><span class="k">PDV</span><span class="v">${esc(r.store.name)} (${esc(r.store.key)})</span></div><div class="row"><span class="k">HUB</span><span class="v">${esc(r.hub.name)}</span></div><div class="row"><span class="k">Ubicación</span><span class="v">${esc(r.hub.city)}, ${esc(r.hub.state)}</span></div><div class="row"><span class="k">Responsable HUB</span><span class="v">${esc(r.hub.owner||'—')}</span></div><div class="row"><span class="k">Persona que entrega</span><span class="v">${esc(r.deliverer||'—')}</span></div></div><table><thead><tr><th>#</th><th>Tipo</th><th>Serie</th><th>Condición</th><th>Notas</th></tr></thead><tbody>${r.equipment.map((e,i)=>`<tr><td>${i+1}</td><td>${esc(e.type)}</td><td>${esc(e.serial)}</td><td>${esc(e.condition)}</td><td>${esc(e.notes)}</td></tr>`).join('')}</tbody></table><div class="sign"><div class="line">Entrega<br>${esc(r.deliverer)}</div><div class="line">Recibe en HUB<br>${esc(r.hub.owner||'')}</div></div><div class="foot">Documento generado desde PRIME MX.</div>${auto?'<script>window.onload=()=>window.print()<\/script>':''}</body></html>`);w.document.close()}
function exportCSV(){if(!requests.length)return toast('No hay solicitudes.',true);const rows=[['Folio','Fecha','Tienda','Clave PDV','HUB','Persona entrega','Tipo','Serie','Condición','Notas']];requests.forEach(r=>r.equipment.forEach(e=>rows.push([r.folio,fmt(r.date),r.store.name,r.store.key,r.hub.name,r.deliverer,e.type,e.serial,e.condition,e.notes])));const csv='﻿'+rows.map(a=>a.map(x=>'"'+String(x??'').replace(/"/g,'""')+'"').join(',')).join('\r\n'),b=new Blob([csv],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='hub_'+new Date().toISOString().slice(0,10)+'.csv';a.click();URL.revokeObjectURL(a.href)}
async function addHub(){if(role!=='ADMIN')return;const region=prompt('Región:');if(!region)return;const state=prompt('Estado:');if(!state)return;const city=prompt('Ciudad:');if(!city)return;const name=prompt('Nombre HUB:');if(!name)return;const owner=prompt('Responsable:')||'',phone=prompt('Teléfono:')||'';const x=await sb.from('hub_locations').insert({region,estado:state,ciudad:city,hub:name,responsable:owner,telefono:phone,activo:true});if(x.error)return toast(x.error.message,true);await loadData();renderAll();toast('HUB agregado')}
async function editHub(id){if(role!=='ADMIN')return;const h=hubs.find(x=>x.id===id);if(!h)return;const region=prompt('Región:',h.region);if(region===null)return;const state=prompt('Estado:',h.estado);if(state===null)return;const city=prompt('Ciudad:',h.ciudad);if(city===null)return;const name=prompt('Nombre HUB:',h.hub);if(name===null)return;const owner=prompt('Responsable:',h.responsable||'');if(owner===null)return;const phone=prompt('Teléfono:',h.telefono||'');if(phone===null)return;const x=await sb.from('hub_locations').update({region,estado:state,ciudad:city,hub:name,responsable:owner,telefono:phone}).eq('id',id);if(x.error)return toast(x.error.message,true);await loadData();renderAll();toast('HUB actualizado')}
async function retireHub(id){if(role!=='ADMIN'||!confirm('¿Retirar este HUB? El histórico no cambia.'))return;const x=await sb.from('hub_locations').update({activo:false}).eq('id',id);if(x.error)return toast(x.error.message,true);await loadData();renderAll();toast('HUB retirado')}
async function init(){try{if(!await auth())return;await loadData();$('#loading').classList.add('hidden');$('#app').classList.remove('hidden');$('#whoName').textContent=profile.nombre||profile.email;$('#whoRole').textContent=role;renderAll()}catch(e){console.error(e);alert('No se pudo cargar HUB: '+(e.message||e));location.href='../'}}
